import math
from typing import List, Dict, Any

# Geographic Boundaries of Chamoli Pilot Region (Uttarakhand)
# Latitudes: 30.20 to 30.80 N, Longitudes: 79.20 to 79.80 E

RAW_HABITATIONS = [
    {
        "id": "HAB-001",
        "name": "Raini Village (Reni)",
        "subdistrict": "Joshimath",
        "latitude": 30.4852,
        "longitude": 79.6914,
        "population": 1250,
        "children_percentage": 22.4,
        "elderly_percentage": 18.2,
        "households": 240,
        "housing_vulnerability_score": 88.0,
        "medical_distance_km": 14.5,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 5,
        "dominant_hazard": "Landslide & Flash Flood",
        "raw_landslide": 92.0,
        "raw_flood": 85.0,
        "raw_slope": 38.0, # degrees
        "river_dist_m": 120.0
    },
    {
        "id": "HAB-002",
        "name": "Joshimath Upper Ward",
        "subdistrict": "Joshimath",
        "latitude": 30.5564,
        "longitude": 79.5642,
        "population": 4800,
        "children_percentage": 19.5,
        "elderly_percentage": 14.8,
        "households": 910,
        "housing_vulnerability_score": 91.0,
        "medical_distance_km": 2.1,
        "road_access_quality": "Moderate",
        "historical_disaster_count": 4,
        "dominant_hazard": "Land Subsidence & Slope Collapse",
        "raw_landslide": 94.0,
        "raw_flood": 40.0,
        "raw_slope": 32.0,
        "river_dist_m": 850.0
    },
    {
        "id": "HAB-003",
        "name": "Tapovan Valley Settlement",
        "subdistrict": "Joshimath",
        "latitude": 30.4935,
        "longitude": 79.6295,
        "population": 1850,
        "children_percentage": 20.1,
        "elderly_percentage": 15.6,
        "households": 340,
        "housing_vulnerability_score": 82.0,
        "medical_distance_km": 11.2,
        "road_access_quality": "Poor",
        "historical_disaster_count": 3,
        "dominant_hazard": "Riverine Inundation & Debris Flow",
        "raw_landslide": 86.0,
        "raw_flood": 92.0,
        "raw_slope": 28.0,
        "river_dist_m": 80.0
    },
    {
        "id": "HAB-004",
        "name": "Helang Slope Habitation",
        "subdistrict": "Joshimath",
        "latitude": 30.5180,
        "longitude": 79.4890,
        "population": 920,
        "children_percentage": 21.0,
        "elderly_percentage": 17.5,
        "households": 180,
        "housing_vulnerability_score": 79.0,
        "medical_distance_km": 18.0,
        "road_access_quality": "Poor",
        "historical_disaster_count": 2,
        "dominant_hazard": "Landslide",
        "raw_landslide": 84.0,
        "raw_flood": 55.0,
        "raw_slope": 34.0,
        "river_dist_m": 450.0
    },
    {
        "id": "HAB-005",
        "name": "Pandukeshwar Village",
        "subdistrict": "Joshimath",
        "latitude": 30.6340,
        "longitude": 79.5490,
        "population": 1600,
        "children_percentage": 18.0,
        "elderly_percentage": 16.0,
        "households": 310,
        "housing_vulnerability_score": 75.0,
        "medical_distance_km": 9.5,
        "road_access_quality": "Moderate",
        "historical_disaster_count": 3,
        "dominant_hazard": "Flash Flood",
        "raw_landslide": 72.0,
        "raw_flood": 88.0,
        "raw_slope": 26.0,
        "river_dist_m": 150.0
    },
    {
        "id": "HAB-006",
        "name": "Mana Village (Border Settlement)",
        "subdistrict": "Joshimath",
        "latitude": 30.7760,
        "longitude": 79.4960,
        "population": 780,
        "children_percentage": 16.5,
        "elderly_percentage": 21.0,
        "households": 160,
        "housing_vulnerability_score": 85.0,
        "medical_distance_km": 24.0,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 4,
        "dominant_hazard": "Extreme Avalanche & Debris",
        "raw_landslide": 78.0,
        "raw_flood": 65.0,
        "raw_slope": 36.0,
        "river_dist_m": 220.0
    },
    {
        "id": "HAB-007",
        "name": "Pipalkoti Valley Ward",
        "subdistrict": "Chamoli",
        "latitude": 30.4320,
        "longitude": 79.4310,
        "population": 3200,
        "children_percentage": 17.2,
        "elderly_percentage": 12.8,
        "households": 620,
        "housing_vulnerability_score": 45.0,
        "medical_distance_km": 3.5,
        "road_access_quality": "Good",
        "historical_disaster_count": 1,
        "dominant_hazard": "Moderate Flood",
        "raw_landslide": 42.0,
        "raw_flood": 58.0,
        "raw_slope": 18.0,
        "river_dist_m": 600.0
    },
    {
        "id": "HAB-008",
        "name": "Chamoli Old Town",
        "subdistrict": "Chamoli",
        "latitude": 30.4040,
        "longitude": 79.3360,
        "population": 5400,
        "children_percentage": 16.0,
        "elderly_percentage": 11.5,
        "households": 1050,
        "housing_vulnerability_score": 55.0,
        "medical_distance_km": 1.2,
        "road_access_quality": "Good",
        "historical_disaster_count": 2,
        "dominant_hazard": "Riverbank Erosion",
        "raw_landslide": 50.0,
        "raw_flood": 68.0,
        "raw_slope": 15.0,
        "river_dist_m": 180.0
    },
    {
        "id": "HAB-009",
        "name": "Tharali Slope Village",
        "subdistrict": "Tharali",
        "latitude": 30.0650,
        "longitude": 79.5020,
        "population": 2100,
        "children_percentage": 21.5,
        "elderly_percentage": 16.8,
        "households": 410,
        "housing_vulnerability_score": 78.0,
        "medical_distance_km": 12.0,
        "road_access_quality": "Poor",
        "historical_disaster_count": 3,
        "dominant_hazard": "Pindar River Flash Flood",
        "raw_landslide": 76.0,
        "raw_flood": 82.0,
        "raw_slope": 29.0,
        "river_dist_m": 140.0
    },
    {
        "id": "HAB-010",
        "name": "Dewal High Village",
        "subdistrict": "Tharali",
        "latitude": 30.0210,
        "longitude": 79.6100,
        "population": 1150,
        "children_percentage": 23.0,
        "elderly_percentage": 19.1,
        "households": 220,
        "housing_vulnerability_score": 80.0,
        "medical_distance_km": 19.5,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 2,
        "dominant_hazard": "Landslide",
        "raw_landslide": 81.0,
        "raw_flood": 35.0,
        "raw_slope": 35.0,
        "river_dist_m": 900.0
    }
]

RAW_CANDIDATE_SITES = [
    {
        "site_id": "SITE-001",
        "id": "SITE-001",
        "name": "Gopeshwar District Relief Campus",
        "address": "Civil Lines, Gopeshwar Town, District Chamoli, Uttarakhand 246401",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4180,
        "longitude": 79.3240,
        "site_type": "Relief Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-001",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 850.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.8,
        "land_area_sqm": 45000.0,
        "water_lpd": 450000,
        "sanitation_cap": 4000,
        "healthcare_cap": 2500,
        "education_cap": 3500,
        "road_cap": 5000,
        "emergency_cap": 4500,
        "safety_score": 92.0,
        "suitability_score": 88.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-002",
        "id": "SITE-002",
        "name": "Government Polytechnic Ground, Pipalkoti",
        "address": "NH-58 Corridor, Pipalkoti, District Chamoli, Uttarakhand 246472",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4410,
        "longitude": 79.4220,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-002",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 600.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 4.2,
        "nearest_hospital_km": 4.2,
        "nearest_school_km": 0.2,
        "land_area_sqm": 22000.0,
        "water_lpd": 200000,
        "sanitation_cap": 1800,
        "healthcare_cap": 1600,
        "education_cap": 2000,
        "road_cap": 2500,
        "emergency_cap": 2000,
        "safety_score": 86.0,
        "suitability_score": 82.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-003",
        "id": "SITE-003",
        "name": "Gauchar Airstrip Relief Complex",
        "address": "Airstrip Grounds, Gauchar, District Chamoli, Uttarakhand 246429",
        "district": "Chamoli",
        "subdistrict": "Karnaprayag",
        "state": "Uttarakhand",
        "latitude": 30.2850,
        "longitude": 79.1580,
        "site_type": "Open Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-003",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 700.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.0,
        "nearest_hospital_km": 2.0,
        "nearest_school_km": 1.1,
        "land_area_sqm": 60000.0,
        "water_lpd": 500000,
        "sanitation_cap": 4800,
        "healthcare_cap": 3000,
        "education_cap": 4000,
        "road_cap": 6000,
        "emergency_cap": 6000,
        "safety_score": 95.0,
        "suitability_score": 91.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-004",
        "id": "SITE-004",
        "name": "Chamoli Sports Stadium Heights",
        "address": "Upper Heights Stadium Complex, Gopeshwar, District Chamoli, Uttarakhand 246401",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4110,
        "longitude": 79.3410,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-004",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 900.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 2.8,
        "nearest_hospital_km": 2.8,
        "nearest_school_km": 0.5,
        "land_area_sqm": 18000.0,
        "water_lpd": 150000,
        "sanitation_cap": 1400,
        "healthcare_cap": 1500,
        "education_cap": 1600,
        "road_cap": 2000,
        "emergency_cap": 1800,
        "safety_score": 84.0,
        "suitability_score": 79.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-005",
        "id": "SITE-005",
        "name": "Tapovan Riverbank Lowland Park",
        "address": "Dhauliganga Riverbank Sector, Tapovan, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4910,
        "longitude": 79.6310,
        "site_type": "Open Ground",
        "source_type": "DEMONSTRATION_DATA",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-005",
        "source_reference": "UK-SDMA Hazard Audit 2026",
        "verification_status": "REJECTED_HAZARD",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": False,
        "safety_status": "REJECTED",
        "rejection_reason": "REJECTED: High Flash Flood Inundation & Landslide Runout Zone (River Distance < 100m)",
        "hazard_status": "UNSAFE_FLOOD_RUNOUT",
        "hazard_reasons": ["Inundation Zone Intersect", "Landslide Runout Area", "River Proximity Buffer < 100m"],
        "river_distance_m": 80.0,
        "road_access_status": "Poor",
        "road_accessibility": "Poor",
        "hospital_distance_km": 12.0,
        "nearest_hospital_km": 12.0,
        "nearest_school_km": 5.0,
        "land_area_sqm": 80000.0,
        "water_lpd": 800000,
        "sanitation_cap": 8000,
        "healthcare_cap": 8000,
        "education_cap": 8000,
        "road_cap": 8000,
        "emergency_cap": 8000,
        "safety_score": 12.0,
        "suitability_score": 10.0,
        "used_capacity": 0,
        "is_demonstration": True,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-006",
        "id": "SITE-006",
        "name": "Joshimath Army Staging Hub & Relief Camp",
        "address": "Upper Plateau Road, Joshimath Town, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.5590,
        "longitude": 79.5680,
        "site_type": "Emergency Staging Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/joshimath/site-006",
        "source_reference": "NDRF & SDMA Emergency Base Registry",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.5,
        "land_area_sqm": 35000.0,
        "water_lpd": 300000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2500,
        "road_cap": 3500,
        "emergency_cap": 3000,
        "safety_score": 89.0,
        "suitability_score": 86.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-007",
        "id": "SITE-007",
        "name": "Tapovan Upper Ridge Community Shelter",
        "address": "Safe Ridge Heights, Tapovan, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4980,
        "longitude": 79.6350,
        "site_type": "Community Centre",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/joshimath/site-007",
        "source_reference": "UK-SDMA District Shelter List 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 450.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 10.5,
        "nearest_hospital_km": 10.5,
        "nearest_school_km": 1.0,
        "land_area_sqm": 15000.0,
        "water_lpd": 150000,
        "sanitation_cap": 1200,
        "healthcare_cap": 1000,
        "education_cap": 1200,
        "road_cap": 1500,
        "emergency_cap": 1500,
        "safety_score": 88.0,
        "suitability_score": 81.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-008",
        "id": "SITE-008",
        "name": "Tharali Sub-Divisional Relief Ground",
        "address": "Main Bazar Heights, Tharali, District Chamoli, Uttarakhand 246481",
        "district": "Chamoli",
        "subdistrict": "Tharali",
        "state": "Uttarakhand",
        "latitude": 30.0680,
        "longitude": 79.5080,
        "site_type": "Government Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/tharali/site-008",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.5,
        "nearest_hospital_km": 2.5,
        "nearest_school_km": 0.4,
        "land_area_sqm": 25000.0,
        "water_lpd": 250000,
        "sanitation_cap": 2200,
        "healthcare_cap": 1800,
        "education_cap": 2000,
        "road_cap": 2500,
        "emergency_cap": 2200,
        "safety_score": 87.0,
        "suitability_score": 83.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-009",
        "id": "SITE-009",
        "name": "Dewal Block High School Shelter",
        "address": "High School Campus, Dewal, District Chamoli, Uttarakhand 246427",
        "district": "Chamoli",
        "subdistrict": "Tharali",
        "state": "Uttarakhand",
        "latitude": 30.0250,
        "longitude": 79.6150,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/dewal/site-009",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 800.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 8.0,
        "nearest_hospital_km": 8.0,
        "nearest_school_km": 0.1,
        "land_area_sqm": 16000.0,
        "water_lpd": 160000,
        "sanitation_cap": 1400,
        "healthcare_cap": 1200,
        "education_cap": 1500,
        "road_cap": 1500,
        "emergency_cap": 1400,
        "safety_score": 85.0,
        "suitability_score": 80.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-010",
        "id": "SITE-010",
        "name": "Karnaprayag Inter College Ground",
        "address": "Alaknanda Confluence Corridor, Karnaprayag, District Chamoli, Uttarakhand 246444",
        "district": "Chamoli",
        "subdistrict": "Karnaprayag",
        "state": "Uttarakhand",
        "latitude": 30.2580,
        "longitude": 79.2150,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/karnaprayag/site-010",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 550.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.8,
        "nearest_hospital_km": 1.8,
        "nearest_school_km": 0.1,
        "land_area_sqm": 28000.0,
        "water_lpd": 280000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2500,
        "road_cap": 3000,
        "emergency_cap": 2500,
        "safety_score": 90.0,
        "suitability_score": 87.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-011",
        "id": "SITE-011",
        "name": "Badrinath High Altitude Transit Shelter",
        "address": "Mana Bypass Sector, Badrinath Town, District Chamoli, Uttarakhand 246422",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.7420,
        "longitude": 79.4910,
        "site_type": "Transit Shelter",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/badrinath/site-011",
        "source_reference": "UK-SDMA High Altitude Relief Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 400.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 3.0,
        "nearest_hospital_km": 3.0,
        "nearest_school_km": 1.5,
        "land_area_sqm": 20000.0,
        "water_lpd": 180000,
        "sanitation_cap": 1500,
        "healthcare_cap": 1200,
        "education_cap": 1500,
        "road_cap": 2000,
        "emergency_cap": 1800,
        "safety_score": 88.0,
        "suitability_score": 84.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-012",
        "id": "SITE-012",
        "name": "Raini Riverbed Flood Plain (UNSAFE TEST)",
        "address": "Rishiganga River Junction, Raini Village, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4840,
        "longitude": 79.6920,
        "site_type": "Open Ground",
        "source_type": "DEMONSTRATION_DATA",
        "source_url": "https://uksdma.uk.gov.in/shelters/raini/site-012",
        "source_reference": "UK-SDMA Hazard Exclusion List 2026",
        "verification_status": "REJECTED_HAZARD",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": False,
        "safety_status": "REJECTED",
        "rejection_reason": "REJECTED: Severe Debris Flow & Flood Plain (River Distance 40m < 100m Buffer)",
        "hazard_status": "UNSAFE_DEBRIS_FLOW",
        "hazard_reasons": ["River Distance < 100m", "Active Debris Channel", "Flash Flood Danger Zone"],
        "river_distance_m": 40.0,
        "road_access_status": "Isolated",
        "road_accessibility": "Isolated",
        "hospital_distance_km": 15.0,
        "nearest_hospital_km": 15.0,
        "nearest_school_km": 3.0,
        "land_area_sqm": 50000.0,
        "water_lpd": 500000,
        "sanitation_cap": 5000,
        "healthcare_cap": 5000,
        "education_cap": 5000,
        "road_cap": 5000,
        "emergency_cap": 5000,
        "safety_score": 15.0,
        "suitability_score": 10.0,
        "used_capacity": 0,
        "is_demonstration": True,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-013",
        "id": "SITE-013",
        "name": "Rishikesh IDPL Relief Complex",
        "address": "IDPL Ground Sector, Rishikesh, District Dehradun, Uttarakhand 249201",
        "district": "Dehradun",
        "subdistrict": "Rishikesh",
        "state": "Uttarakhand",
        "latitude": 30.1030,
        "longitude": 78.2930,
        "site_type": "State Relief Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/rishikesh/site-013",
        "source_reference": "Uttarakhand State Master Shelter Plan 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.5,
        "land_area_sqm": 100000.0,
        "water_lpd": 1000000,
        "sanitation_cap": 9000,
        "healthcare_cap": 8000,
        "education_cap": 9000,
        "road_cap": 10000,
        "emergency_cap": 10000,
        "safety_score": 96.0,
        "suitability_score": 94.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Telangana SDMA Verified Master Shelters & MPRCs
    {
        "site_id": "SITE-014",
        "id": "SITE-014",
        "name": "Medchal Municipal Multipurpose Relief Center",
        "address": "Near NH-44 Bypass Corridor, Medchal Town, Medchal-Malkajgiri, Telangana 501401",
        "district": "Medchal-Malkajgiri",
        "subdistrict": "Medchal",
        "state": "Telangana",
        "latitude": 17.6295,
        "longitude": 78.4814,
        "site_type": "Relief Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://tg-sdma.telangana.gov.in/shelters/medchal/site-014",
        "source_reference": "Telangana SDMA Master Emergency Facility Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.4,
        "land_area_sqm": 35000.0,
        "water_lpd": 350000,
        "sanitation_cap": 3000,
        "healthcare_cap": 2500,
        "education_cap": 3000,
        "road_cap": 4000,
        "emergency_cap": 3500,
        "safety_score": 94.0,
        "suitability_score": 91.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-015",
        "id": "SITE-015",
        "name": "Kompally Sports Complex & Relief Hub",
        "address": "Dulapally Road, Kompally, Medchal-Malkajgiri, Telangana 500100",
        "district": "Medchal-Malkajgiri",
        "subdistrict": "Quthbullapur",
        "state": "Telangana",
        "latitude": 17.5450,
        "longitude": 78.4820,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://tg-sdma.telangana.gov.in/shelters/kompally/site-015",
        "source_reference": "Telangana SDMA Master Emergency Facility Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.1,
        "nearest_hospital_km": 2.1,
        "nearest_school_km": 0.6,
        "land_area_sqm": 40000.0,
        "water_lpd": 400000,
        "sanitation_cap": 3500,
        "healthcare_cap": 3000,
        "education_cap": 3500,
        "road_cap": 4500,
        "emergency_cap": 4000,
        "safety_score": 92.5,
        "suitability_score": 89.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-016",
        "id": "SITE-016",
        "name": "Gachibowli Stadium Disaster Relief Complex",
        "address": "Old Mumbai Highway, Gachibowli, Hyderabad, Telangana 500032",
        "district": "Hyderabad",
        "subdistrict": "Serilingampally",
        "state": "Telangana",
        "latitude": 17.4435,
        "longitude": 78.3482,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://tg-sdma.telangana.gov.in/shelters/gachibowli/site-016",
        "source_reference": "Telangana SDMA Master Emergency Facility Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.8,
        "land_area_sqm": 80000.0,
        "water_lpd": 800000,
        "sanitation_cap": 6000,
        "healthcare_cap": 5000,
        "education_cap": 6000,
        "road_cap": 7000,
        "emergency_cap": 6000,
        "safety_score": 96.0,
        "suitability_score": 94.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-017",
        "id": "SITE-017",
        "name": "Bhadrachalam High Ground ITDA Relief Campus",
        "address": "High Ground Colony, Subhash Nagar, Bhadrachalam, Bhadradri Kothagudem, Telangana 507111",
        "district": "Bhadradri Kothagudem",
        "subdistrict": "Bhadrachalam",
        "state": "Telangana",
        "latitude": 17.6790,
        "longitude": 80.8810,
        "site_type": "Relief Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://tg-sdma.telangana.gov.in/shelters/bhadrachalam/site-017",
        "source_reference": "Telangana SDMA Master Emergency Facility Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1800.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.8,
        "nearest_hospital_km": 1.8,
        "nearest_school_km": 0.5,
        "land_area_sqm": 32000.0,
        "water_lpd": 300000,
        "sanitation_cap": 3000,
        "healthcare_cap": 2200,
        "education_cap": 2500,
        "road_cap": 3000,
        "emergency_cap": 2800,
        "safety_score": 91.0,
        "suitability_score": 87.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Andhra Pradesh SDMA Master Relief Facilities
    {
        "site_id": "SITE-018",
        "id": "SITE-018",
        "name": "Andhra University Relief Ground & Cyclone Shelter",
        "address": "AU Campus, Waltair Uplands, Visakhapatnam, Andhra Pradesh 530003",
        "district": "Visakhapatnam",
        "subdistrict": "Visakhapatnam Urban",
        "state": "Andhra Pradesh",
        "latitude": 17.7280,
        "longitude": 83.3190,
        "site_type": "University Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://apsdma.ap.gov.in/shelters/visakhapatnam/site-018",
        "source_reference": "AP State Disaster Management Authority Shelter Network 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.2,
        "land_area_sqm": 65000.0,
        "water_lpd": 600000,
        "sanitation_cap": 5000,
        "healthcare_cap": 4000,
        "education_cap": 5000,
        "road_cap": 6000,
        "emergency_cap": 5000,
        "safety_score": 95.0,
        "suitability_score": 92.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-019",
        "id": "SITE-019",
        "name": "Government Arts College High Ground Relief Center",
        "address": "Arts College Road, Rajamahendravaram, East Godavari, Andhra Pradesh 533105",
        "district": "East Godavari",
        "subdistrict": "Rajahmundry",
        "state": "Andhra Pradesh",
        "latitude": 17.0120,
        "longitude": 81.7920,
        "site_type": "College Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://apsdma.ap.gov.in/shelters/east-godavari/site-019",
        "source_reference": "AP State Disaster Management Authority Shelter Network 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2100.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.6,
        "nearest_hospital_km": 1.6,
        "nearest_school_km": 0.3,
        "land_area_sqm": 45000.0,
        "water_lpd": 400000,
        "sanitation_cap": 3500,
        "healthcare_cap": 3000,
        "education_cap": 3500,
        "road_cap": 4500,
        "emergency_cap": 3500,
        "safety_score": 93.0,
        "suitability_score": 89.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Maharashtra SDMA Master Relief Facilities
    {
        "site_id": "SITE-020",
        "id": "SITE-020",
        "name": "Shiv Chhatrapati Balewadi Sports Complex",
        "address": "Balewadi High Street, Pune, Maharashtra 411045",
        "district": "Pune",
        "subdistrict": "Haveli",
        "state": "Maharashtra",
        "latitude": 18.5793,
        "longitude": 73.7744,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://mahasdma.maharashtra.gov.in/shelters/pune/site-020",
        "source_reference": "Maharashtra State Disaster Management Master Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.4,
        "nearest_hospital_km": 1.4,
        "nearest_school_km": 0.8,
        "land_area_sqm": 120000.0,
        "water_lpd": 1200000,
        "sanitation_cap": 9000,
        "healthcare_cap": 7500,
        "education_cap": 9000,
        "road_cap": 10000,
        "emergency_cap": 9000,
        "safety_score": 96.0,
        "suitability_score": 93.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-021",
        "id": "SITE-021",
        "name": "BKC MMRDA Disaster Evacuation & Relief Ground",
        "address": "G Block, Bandra Kurla Complex, Mumbai Suburban, Maharashtra 400051",
        "district": "Mumbai Suburban",
        "subdistrict": "Bandra",
        "state": "Maharashtra",
        "latitude": 19.0657,
        "longitude": 72.8688,
        "site_type": "Exhibition & Relief Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://mahasdma.maharashtra.gov.in/shelters/mumbai/site-021",
        "source_reference": "Maharashtra State Disaster Management Master Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.9,
        "land_area_sqm": 75000.0,
        "water_lpd": 700000,
        "sanitation_cap": 6000,
        "healthcare_cap": 5000,
        "education_cap": 5500,
        "road_cap": 7000,
        "emergency_cap": 6000,
        "safety_score": 91.5,
        "suitability_score": 90.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Gujarat GSDMA Master Relief Facilities
    {
        "site_id": "SITE-022",
        "id": "SITE-022",
        "name": "Radhanpur Sub-Divisional Emergency Shelter",
        "address": "High School Ground Sector, Radhanpur, Patan, Gujarat 385340",
        "district": "Patan",
        "subdistrict": "Radhanpur",
        "state": "Gujarat",
        "latitude": 23.8340,
        "longitude": 71.6120,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://gsdma.gujarat.gov.in/shelters/patan/site-022",
        "source_reference": "GSDMA Gujarat State Shelter Directory 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2800.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.0,
        "nearest_hospital_km": 2.0,
        "nearest_school_km": 0.2,
        "land_area_sqm": 30000.0,
        "water_lpd": 250000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2500,
        "road_cap": 3000,
        "emergency_cap": 2500,
        "safety_score": 90.0,
        "suitability_score": 86.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-023",
        "id": "SITE-023",
        "name": "Bhuj Jubilee Ground Disaster Relief Camp",
        "address": "Jubilee Ground Road, Bhuj, Kutch, Gujarat 370001",
        "district": "Kutch",
        "subdistrict": "Bhuj",
        "state": "Gujarat",
        "latitude": 23.2550,
        "longitude": 69.6690,
        "site_type": "Open Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://gsdma.gujarat.gov.in/shelters/kutch/site-023",
        "source_reference": "GSDMA Gujarat State Shelter Directory 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.7,
        "land_area_sqm": 50000.0,
        "water_lpd": 450000,
        "sanitation_cap": 4000,
        "healthcare_cap": 3200,
        "education_cap": 4000,
        "road_cap": 5000,
        "emergency_cap": 4000,
        "safety_score": 92.0,
        "suitability_score": 88.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Bihar BSDMA Master Relief Facilities
    {
        "site_id": "SITE-024",
        "id": "SITE-024",
        "name": "Supaul ITI High Ground Emergency Relief Camp",
        "address": "Near District Collectorate, Supaul, Bihar 852131",
        "district": "Supaul",
        "subdistrict": "Supaul",
        "state": "Bihar",
        "latitude": 26.1260,
        "longitude": 86.6080,
        "site_type": "Technical Institute Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://bsdma.bihar.gov.in/shelters/supaul/site-024",
        "source_reference": "Bihar State Disaster Management Authority Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.8,
        "nearest_hospital_km": 1.8,
        "nearest_school_km": 0.3,
        "land_area_sqm": 40000.0,
        "water_lpd": 350000,
        "sanitation_cap": 3500,
        "healthcare_cap": 2600,
        "education_cap": 3000,
        "road_cap": 4000,
        "emergency_cap": 3200,
        "safety_score": 92.5,
        "suitability_score": 88.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-025",
        "id": "SITE-025",
        "name": "Darbhanga Raj Maidan Disaster Relief Campus",
        "address": "Raj High School Sector, Darbhanga, Bihar 846004",
        "district": "Darbhanga",
        "subdistrict": "Darbhanga",
        "state": "Bihar",
        "latitude": 26.1520,
        "longitude": 85.8970,
        "site_type": "College Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://bsdma.bihar.gov.in/shelters/darbhanga/site-025",
        "source_reference": "Bihar State Disaster Management Authority Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2400.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.4,
        "land_area_sqm": 42000.0,
        "water_lpd": 380000,
        "sanitation_cap": 3200,
        "healthcare_cap": 2500,
        "education_cap": 3000,
        "road_cap": 3800,
        "emergency_cap": 3000,
        "safety_score": 91.0,
        "suitability_score": 87.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Kerala KSDMA Master Relief Facilities
    {
        "site_id": "SITE-026",
        "id": "SITE-026",
        "name": "Meppadi Community High Ground Relief Center",
        "address": "Government High School Heights, Meppadi, Wayanad, Kerala 673577",
        "district": "Wayanad",
        "subdistrict": "Vythiri",
        "state": "Kerala",
        "latitude": 11.5510,
        "longitude": 76.1260,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://sdma.kerala.gov.in/shelters/wayanad/site-026",
        "source_reference": "Kerala State Disaster Management Authority Network 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1600.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.0,
        "nearest_hospital_km": 2.0,
        "nearest_school_km": 0.1,
        "land_area_sqm": 28000.0,
        "water_lpd": 280000,
        "sanitation_cap": 2200,
        "healthcare_cap": 1800,
        "education_cap": 2000,
        "road_cap": 2500,
        "emergency_cap": 2200,
        "safety_score": 93.0,
        "suitability_score": 89.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Assam ASDMA Master Relief Facilities
    {
        "site_id": "SITE-027",
        "id": "SITE-027",
        "name": "Sarusajai National Stadium Disaster Relief Hub",
        "address": "Lokhra Road, Sarusajai, Guwahati, Kamrup Metropolitan, Assam 781040",
        "district": "Kamrup Metropolitan",
        "subdistrict": "Guwahati",
        "state": "Assam",
        "latitude": 26.1150,
        "longitude": 91.7370,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://asdma.assam.gov.in/shelters/guwahati/site-027",
        "source_reference": "Assam State Disaster Management Authority Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 4000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.5,
        "land_area_sqm": 95000.0,
        "water_lpd": 900000,
        "sanitation_cap": 7500,
        "healthcare_cap": 6000,
        "education_cap": 7000,
        "road_cap": 8500,
        "emergency_cap": 7500,
        "safety_score": 95.5,
        "suitability_score": 92.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Odisha OSDMA Master Relief Facilities
    {
        "site_id": "SITE-028",
        "id": "SITE-028",
        "name": "Kalinga Stadium Multi-Disaster Relief Hub",
        "address": "Biju Patnaik Colony, Nayapalli, Bhubaneswar, Khurda, Odisha 751012",
        "district": "Khurda",
        "subdistrict": "Bhubaneswar",
        "state": "Odisha",
        "latitude": 20.2925,
        "longitude": 85.8236,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://osdma.odisha.gov.in/shelters/bhubaneswar/site-028",
        "source_reference": "Odisha State Disaster Management Authority Shelter Network 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.6,
        "land_area_sqm": 90000.0,
        "water_lpd": 850000,
        "sanitation_cap": 7000,
        "healthcare_cap": 5500,
        "education_cap": 6500,
        "road_cap": 8000,
        "emergency_cap": 7000,
        "safety_score": 96.5,
        "suitability_score": 93.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # West Bengal WBSDMA Master Relief Facilities
    {
        "site_id": "SITE-029",
        "id": "SITE-029",
        "name": "Salt Lake Stadium Emergency Evacuation Campus",
        "address": "JB Block, Sector III, Bidhannagar, Kolkata, West Bengal 700098",
        "district": "North 24 Parganas",
        "subdistrict": "Bidhannagar",
        "state": "West Bengal",
        "latitude": 22.5697,
        "longitude": 88.4072,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://wbsdma.wb.gov.in/shelters/kolkata/site-029",
        "source_reference": "West Bengal State Disaster Management Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2800.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.7,
        "land_area_sqm": 110000.0,
        "water_lpd": 1000000,
        "sanitation_cap": 8500,
        "healthcare_cap": 7000,
        "education_cap": 8000,
        "road_cap": 9000,
        "emergency_cap": 8000,
        "safety_score": 95.0,
        "suitability_score": 91.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Rajasthan DM&R Master Relief Facilities
    {
        "site_id": "SITE-030",
        "id": "SITE-030",
        "name": "Sawai Mansingh Stadium Relief Complex",
        "address": "Amar Jawan Jyoti Corridor, Jan Path, Jaipur, Rajasthan 302005",
        "district": "Jaipur",
        "subdistrict": "Jaipur",
        "state": "Rajasthan",
        "latitude": 26.8928,
        "longitude": 75.8048,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://dmr.rajasthan.gov.in/shelters/jaipur/site-030",
        "source_reference": "Rajasthan Disaster Management & Relief Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 4500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.5,
        "land_area_sqm": 85000.0,
        "water_lpd": 800000,
        "sanitation_cap": 6500,
        "healthcare_cap": 5000,
        "education_cap": 6000,
        "road_cap": 7500,
        "emergency_cap": 6500,
        "safety_score": 96.0,
        "suitability_score": 93.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Tamil Nadu TNDMA Master Relief Facilities
    {
        "site_id": "SITE-031",
        "id": "SITE-031",
        "name": "Jawaharlal Nehru Stadium Emergency Evacuation Center",
        "address": "Sydenhams Road, Periyamet, Chennai, Tamil Nadu 600003",
        "district": "Chennai",
        "subdistrict": "Periyamet",
        "state": "Tamil Nadu",
        "latitude": 13.0837,
        "longitude": 80.2747,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://tnsdma.tn.gov.in/shelters/chennai/site-031",
        "source_reference": "Tamil Nadu State Disaster Management Master Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1800.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.6,
        "land_area_sqm": 80000.0,
        "water_lpd": 750000,
        "sanitation_cap": 6000,
        "healthcare_cap": 5000,
        "education_cap": 5500,
        "road_cap": 7000,
        "emergency_cap": 6000,
        "safety_score": 94.5,
        "suitability_score": 91.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Karnataka KSDMA Master Relief Facilities
    {
        "site_id": "SITE-032",
        "id": "SITE-032",
        "name": "Sree Kanteerava Stadium Disaster Relief Complex",
        "address": "Kasturba Road, Sampangi Rama Nagara, Bengaluru, Karnataka 560001",
        "district": "Bengaluru Urban",
        "subdistrict": "Bengaluru Central",
        "state": "Karnataka",
        "latitude": 12.9698,
        "longitude": 77.5926,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://ksdma.karnataka.gov.in/shelters/bengaluru/site-032",
        "source_reference": "Karnataka State Disaster Management Authority Directory 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 5000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 0.8,
        "nearest_hospital_km": 0.8,
        "nearest_school_km": 0.5,
        "land_area_sqm": 90000.0,
        "water_lpd": 850000,
        "sanitation_cap": 7000,
        "healthcare_cap": 5500,
        "education_cap": 6500,
        "road_cap": 8000,
        "emergency_cap": 7000,
        "safety_score": 97.0,
        "suitability_score": 94.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Himachal Pradesh HPSDMA Master Relief Facilities
    {
        "site_id": "SITE-033",
        "id": "SITE-033",
        "name": "Dhalpur High Ground Disaster Relief Center",
        "address": "Dhalpur Ground Sector, Kullu, Himachal Pradesh 175101",
        "district": "Kullu",
        "subdistrict": "Kullu",
        "state": "Himachal Pradesh",
        "latitude": 31.9560,
        "longitude": 77.1080,
        "site_type": "Relief Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://hpsdma.nic.in/shelters/kullu/site-033",
        "source_reference": "HP State Disaster Management Authority Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 800.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.4,
        "land_area_sqm": 35000.0,
        "water_lpd": 300000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2200,
        "road_cap": 2800,
        "emergency_cap": 2500,
        "safety_score": 91.0,
        "suitability_score": 86.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Sikkim SSDMA Master Relief Facilities
    {
        "site_id": "SITE-034",
        "id": "SITE-034",
        "name": "Paljor Stadium High Altitude Relief Campus",
        "address": "Paljor Stadium Road, Gangtok, East Sikkim, Sikkim 737101",
        "district": "East Sikkim",
        "subdistrict": "Gangtok",
        "state": "Sikkim",
        "latitude": 27.3320,
        "longitude": 88.6140,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://ssdma.nic.in/shelters/gangtok/site-034",
        "source_reference": "Sikkim State Disaster Management Authority Registry 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.4,
        "nearest_hospital_km": 1.4,
        "nearest_school_km": 0.3,
        "land_area_sqm": 30000.0,
        "water_lpd": 250000,
        "sanitation_cap": 2200,
        "healthcare_cap": 1800,
        "education_cap": 2000,
        "road_cap": 2400,
        "emergency_cap": 2000,
        "safety_score": 92.0,
        "suitability_score": 87.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Andaman and Nicobar Islands Relief Facilities
    {
        "site_id": "SITE-035",
        "id": "SITE-035",
        "name": "Netaji Stadium Tsunami & Cyclone Relief Hub",
        "address": "Aberdeen Bazar, Port Blair, South Andaman, Andaman and Nicobar Islands 744101",
        "district": "South Andaman",
        "subdistrict": "Port Blair",
        "state": "Andaman and Nicobar Islands",
        "latitude": 11.6680,
        "longitude": 92.7420,
        "site_type": "Stadium Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://andaman.gov.in/shelters/port-blair/site-035",
        "source_reference": "A&N Directorate of Disaster Management Master Plan 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.5,
        "land_area_sqm": 40000.0,
        "water_lpd": 350000,
        "sanitation_cap": 3000,
        "healthcare_cap": 2500,
        "education_cap": 2800,
        "road_cap": 3500,
        "emergency_cap": 3000,
        "safety_score": 93.0,
        "suitability_score": 89.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Madhya Pradesh MPSDMA Master Relief Facilities
    {
        "site_id": "SITE-036",
        "id": "SITE-036",
        "name": "TT Nagar Stadium Disaster Relief Hub",
        "address": "Stadium Road, TT Nagar, Bhopal, Madhya Pradesh 462003",
        "district": "Bhopal",
        "subdistrict": "Bhopal Urban",
        "state": "Madhya Pradesh",
        "latitude": 23.2370,
        "longitude": 77.4010,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://sdma.mp.gov.in/shelters/bhopal/site-036",
        "source_reference": "MP State Disaster Management Authority Master Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 3500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.1,
        "nearest_hospital_km": 1.1,
        "nearest_school_km": 0.6,
        "land_area_sqm": 70000.0,
        "water_lpd": 650000,
        "sanitation_cap": 5500,
        "healthcare_cap": 4500,
        "education_cap": 5000,
        "road_cap": 6500,
        "emergency_cap": 5500,
        "safety_score": 96.0,
        "suitability_score": 92.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Chhattisgarh CSDMA Master Relief Facilities
    {
        "site_id": "SITE-037",
        "id": "SITE-037",
        "name": "Balbir Singh Juneja Indoor Stadium Relief Camp",
        "address": "Budha Para, Raipur, Chhattisgarh 492001",
        "district": "Raipur",
        "subdistrict": "Raipur Urban",
        "state": "Chhattisgarh",
        "latitude": 21.2380,
        "longitude": 81.6360,
        "site_type": "Indoor Stadium",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://csdma.cg.gov.in/shelters/raipur/site-037",
        "source_reference": "Chhattisgarh State Disaster Management Authority 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 4000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.3,
        "nearest_hospital_km": 1.3,
        "nearest_school_km": 0.5,
        "land_area_sqm": 55000.0,
        "water_lpd": 500000,
        "sanitation_cap": 4500,
        "healthcare_cap": 3800,
        "education_cap": 4200,
        "road_cap": 5500,
        "emergency_cap": 4500,
        "safety_score": 95.0,
        "suitability_score": 91.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    # Uttar Pradesh UPSDMA Master Relief Facilities
    {
        "site_id": "SITE-038",
        "id": "SITE-038",
        "name": "K. D. Singh Babu Stadium Relief Complex",
        "address": "Hazratganj, Lucknow, Uttar Pradesh 226001",
        "district": "Lucknow",
        "subdistrict": "Lucknow Urban",
        "state": "Uttar Pradesh",
        "latitude": 26.8520,
        "longitude": 80.9380,
        "site_type": "Stadium Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://upsdma.up.gov.in/shelters/lucknow/site-038",
        "source_reference": "UP State Disaster Management Authority Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-25T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 2000.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 0.9,
        "nearest_hospital_km": 0.9,
        "nearest_school_km": 0.4,
        "land_area_sqm": 80000.0,
        "water_lpd": 750000,
        "sanitation_cap": 6000,
        "healthcare_cap": 5000,
        "education_cap": 5500,
        "road_cap": 7000,
        "emergency_cap": 6000,
        "safety_score": 96.0,
        "suitability_score": 93.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    }
]


DATA_SOURCES = [
    {
        "id": "DS-001",
        "source_name": "ISRO Bhuvan GIS",
        "dataset_name": "National Landslide Susceptibility Map (Himalayan Belt)",
        "purpose": "Geospatial landslide slope hazard scoring",
        "spatial_resolution": "30m DEM Grid",
        "temporal_resolution": "Seasonal / Bi-annual",
        "last_updated": "2026-05-15",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-002",
        "source_name": "ISRO MOSDAC",
        "dataset_name": "INSAT-3D Hourly Gridded Precipitation",
        "purpose": "Dynamic rainfall intensity & extreme weather simulation",
        "spatial_resolution": "0.1 deg (~10km)",
        "temporal_resolution": "Hourly",
        "last_updated": "2026-09-09 22:00 IST",
        "status": "CONNECTED"
    },
    {
        "id": "DS-003",
        "source_name": "Census India / UK-SDMA",
        "dataset_name": "District Settlement Population & Vulnerability Baseline",
        "purpose": "Population demographics, elderly/children count, households",
        "spatial_resolution": "Habitation / Village Level",
        "temporal_resolution": "Baseline",
        "last_updated": "2024-11-20",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-004",
        "source_name": "OpenStreetMap / PWD UK",
        "dataset_name": "Himalayan Mountain Road Network & Infrastructure",
        "purpose": "Accessibility routing & medical proximity",
        "spatial_resolution": "Vector Line String",
        "temporal_resolution": "Continuous",
        "last_updated": "2026-08-01",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-005",
        "source_name": "AASHRAY Simulation Engine",
        "dataset_name": "Extreme Cloudburst Scenario Generator (Chamoli Pilot)",
        "purpose": "Dynamic risk recalculation & decision-support testing",
        "spatial_resolution": "100m Hydro Grid",
        "temporal_resolution": "Real-time interactive",
        "last_updated": "Active Engine",
        "status": "SIMULATED"
    }
]

INITIAL_ALERTS = [
    {
        "id": "ALT-001",
        "severity": "CRITICAL",
        "timestamp": "2026-09-11 00:15",
        "source": "IMD District Warning System",
        "location": "Chamoli & Upper Alaknanda Catchment",
        "message": "IMD Heavy to Very Heavy Rainfall Warning (Orange Alert). High Risk of Slope Instability."
    },
    {
        "id": "ALT-002",
        "severity": "WARNING",
        "timestamp": "2026-09-11 00:10",
        "source": "AASHRAY Carrying Capacity Engine",
        "location": "Gopeshwar District Relief Campus",
        "message": "Healthcare capacity bottleneck identified (Healthcare cap threshold: 2,500 persons)."
    },
    {
        "id": "ALT-003",
        "severity": "WARNING",
        "timestamp": "2026-09-10 21:15",
        "source": "Ground Field Officer Observation (NDRF-44)",
        "location": "Raini Upper Settlement Cluster",
        "message": "Active tension cracks observed 40m above residential cluster. Water seepage visible."
    }
]


RIVERS_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {"name": "Alaknanda River", "type": "Major Himalayan River"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.4960, 30.7760],
                    [79.5490, 30.6340],
                    [79.5642, 30.5564],
                    [79.4310, 30.4320],
                    [79.3360, 30.4040],
                    [79.1580, 30.2850]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Dhauliganga River", "type": "Flash Flood Drainage Channel"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.6914, 30.4852],
                    [79.6295, 30.4935],
                    [79.5642, 30.5564]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Pindar River", "type": "South Chamoli Tributary"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.6100, 30.0210],
                    [79.5020, 30.0650],
                    [79.3360, 30.4040]
                ]
            }
        }
    ]
}

ROADS_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {"name": "Badrinath Highway (NH-58)", "type": "Arterial Highway"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.1580, 30.2850],
                    [79.3360, 30.4040],
                    [79.4310, 30.4320],
                    [79.4890, 30.5180],
                    [79.5642, 30.5564],
                    [79.5490, 30.6340],
                    [79.4960, 30.7760]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Joshimath - Malari Border Road", "type": "Strategic Mountain Corridor"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.5642, 30.5564],
                    [79.6295, 30.4935],
                    [79.6914, 30.4852]
                ]
            }
        }
    ]
}

INFRASTRUCTURE_FACILITIES = {
    "hospitals": [
        {"id": "HOSP-01", "name": "District Hospital Gopeshwar", "latitude": 30.4190, "longitude": 79.3250, "beds": 150, "icu_available": True},
        {"id": "HOSP-02", "name": "Sub-District Hospital Joshimath", "latitude": 30.5570, "longitude": 79.5650, "beds": 60, "icu_available": False},
        {"id": "HOSP-03", "name": "CHC Pipalkoti", "latitude": 30.4330, "longitude": 79.4320, "beds": 30, "icu_available": False},
        {"id": "HOSP-04", "name": "Primary Health Centre Tapovan", "latitude": 30.4940, "longitude": 79.6300, "beds": 15, "icu_available": False}
    ],
    "schools": [
        {"id": "SCH-01", "name": "Govt Inter College Joshimath", "latitude": 30.5580, "longitude": 79.5630, "capacity": 800},
        {"id": "SCH-02", "name": "Govt Polytechnic Pipalkoti", "latitude": 30.4410, "longitude": 79.4220, "capacity": 1200},
        {"id": "SCH-03", "name": "Primary School Raini", "latitude": 30.4860, "longitude": 79.6920, "capacity": 150},
        {"id": "SCH-04", "name": "GIC Gopeshwar Central", "latitude": 30.4170, "longitude": 79.3230, "capacity": 1000}
    ],
    "emergency_centres": [
        {"id": "EMERG-01", "name": "NDRF 15th Bn Base Camp, Joshimath", "latitude": 30.5550, "longitude": 79.5610, "teams_deployed": 4},
        {"id": "EMERG-02", "name": "DEOC Control Room, Gopeshwar", "latitude": 30.4185, "longitude": 79.3245, "teams_deployed": 6},
        {"id": "EMERG-03", "name": "Army Staging Hub, Gauchar Airstrip", "latitude": 30.2855, "longitude": 79.1585, "teams_deployed": 8}
    ]
}

