import math
from typing import List, Dict, Any

# Geographic Boundaries of Chamoli Pilot Region (Uttarakhand)
# Latitudes: 30.20 to 30.80 N, Longitudes: 79.20 to 79.80 E

RAW_HABITATIONS = [
    {
        "id": "HAB-001",
        "name": "Raini Village (Reni)",
        "subdistrict": "Joshimath",
        "latitude": 30.4852,
        "longitude": 79.6914,
        "population": 1250,
        "children_percentage": 22.4,
        "elderly_percentage": 18.2,
        "households": 240,
        "housing_vulnerability_score": 88.0,
        "medical_distance_km": 14.5,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 5,
        "dominant_hazard": "Landslide & Flash Flood",
        "raw_landslide": 92.0,
        "raw_flood": 85.0,
        "raw_slope": 38.0, # degrees
        "river_dist_m": 120.0
    },
    {
        "id": "HAB-002",
        "name": "Joshimath Upper Ward",
        "subdistrict": "Joshimath",
        "latitude": 30.5564,
        "longitude": 79.5642,
        "population": 4800,
        "children_percentage": 19.5,
        "elderly_percentage": 14.8,
        "households": 910,
        "housing_vulnerability_score": 91.0,
        "medical_distance_km": 2.1,
        "road_access_quality": "Moderate",
        "historical_disaster_count": 4,
        "dominant_hazard": "Land Subsidence & Slope Collapse",
        "raw_landslide": 94.0,
        "raw_flood": 40.0,
        "raw_slope": 32.0,
        "river_dist_m": 850.0
    },
    {
        "id": "HAB-003",
        "name": "Tapovan Valley Settlement",
        "subdistrict": "Joshimath",
        "latitude": 30.4935,
        "longitude": 79.6295,
        "population": 1850,
        "children_percentage": 20.1,
        "elderly_percentage": 15.6,
        "households": 340,
        "housing_vulnerability_score": 82.0,
        "medical_distance_km": 11.2,
        "road_access_quality": "Poor",
        "historical_disaster_count": 3,
        "dominant_hazard": "Riverine Inundation & Debris Flow",
        "raw_landslide": 86.0,
        "raw_flood": 92.0,
        "raw_slope": 28.0,
        "river_dist_m": 80.0
    },
    {
        "id": "HAB-004",
        "name": "Helang Slope Habitation",
        "subdistrict": "Joshimath",
        "latitude": 30.5180,
        "longitude": 79.4890,
        "population": 920,
        "children_percentage": 21.0,
        "elderly_percentage": 17.5,
        "households": 180,
        "housing_vulnerability_score": 79.0,
        "medical_distance_km": 18.0,
        "road_access_quality": "Poor",
        "historical_disaster_count": 2,
        "dominant_hazard": "Landslide",
        "raw_landslide": 84.0,
        "raw_flood": 55.0,
        "raw_slope": 34.0,
        "river_dist_m": 450.0
    },
    {
        "id": "HAB-005",
        "name": "Pandukeshwar Village",
        "subdistrict": "Joshimath",
        "latitude": 30.6340,
        "longitude": 79.5490,
        "population": 1600,
        "children_percentage": 18.0,
        "elderly_percentage": 16.0,
        "households": 310,
        "housing_vulnerability_score": 75.0,
        "medical_distance_km": 9.5,
        "road_access_quality": "Moderate",
        "historical_disaster_count": 3,
        "dominant_hazard": "Flash Flood",
        "raw_landslide": 72.0,
        "raw_flood": 88.0,
        "raw_slope": 26.0,
        "river_dist_m": 150.0
    },
    {
        "id": "HAB-006",
        "name": "Mana Village (Border Settlement)",
        "subdistrict": "Joshimath",
        "latitude": 30.7760,
        "longitude": 79.4960,
        "population": 780,
        "children_percentage": 16.5,
        "elderly_percentage": 21.0,
        "households": 160,
        "housing_vulnerability_score": 85.0,
        "medical_distance_km": 24.0,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 4,
        "dominant_hazard": "Extreme Avalanche & Debris",
        "raw_landslide": 78.0,
        "raw_flood": 65.0,
        "raw_slope": 36.0,
        "river_dist_m": 220.0
    },
    {
        "id": "HAB-007",
        "name": "Pipalkoti Valley Ward",
        "subdistrict": "Chamoli",
        "latitude": 30.4320,
        "longitude": 79.4310,
        "population": 3200,
        "children_percentage": 17.2,
        "elderly_percentage": 12.8,
        "households": 620,
        "housing_vulnerability_score": 45.0,
        "medical_distance_km": 3.5,
        "road_access_quality": "Good",
        "historical_disaster_count": 1,
        "dominant_hazard": "Moderate Flood",
        "raw_landslide": 42.0,
        "raw_flood": 58.0,
        "raw_slope": 18.0,
        "river_dist_m": 600.0
    },
    {
        "id": "HAB-008",
        "name": "Chamoli Old Town",
        "subdistrict": "Chamoli",
        "latitude": 30.4040,
        "longitude": 79.3360,
        "population": 5400,
        "children_percentage": 16.0,
        "elderly_percentage": 11.5,
        "households": 1050,
        "housing_vulnerability_score": 55.0,
        "medical_distance_km": 1.2,
        "road_access_quality": "Good",
        "historical_disaster_count": 2,
        "dominant_hazard": "Riverbank Erosion",
        "raw_landslide": 50.0,
        "raw_flood": 68.0,
        "raw_slope": 15.0,
        "river_dist_m": 180.0
    },
    {
        "id": "HAB-009",
        "name": "Tharali Slope Village",
        "subdistrict": "Tharali",
        "latitude": 30.0650,
        "longitude": 79.5020,
        "population": 2100,
        "children_percentage": 21.5,
        "elderly_percentage": 16.8,
        "households": 410,
        "housing_vulnerability_score": 78.0,
        "medical_distance_km": 12.0,
        "road_access_quality": "Poor",
        "historical_disaster_count": 3,
        "dominant_hazard": "Pindar River Flash Flood",
        "raw_landslide": 76.0,
        "raw_flood": 82.0,
        "raw_slope": 29.0,
        "river_dist_m": 140.0
    },
    {
        "id": "HAB-010",
        "name": "Dewal High Village",
        "subdistrict": "Tharali",
        "latitude": 30.0210,
        "longitude": 79.6100,
        "population": 1150,
        "children_percentage": 23.0,
        "elderly_percentage": 19.1,
        "households": 220,
        "housing_vulnerability_score": 80.0,
        "medical_distance_km": 19.5,
        "road_access_quality": "Isolated",
        "historical_disaster_count": 2,
        "dominant_hazard": "Landslide",
        "raw_landslide": 81.0,
        "raw_flood": 35.0,
        "raw_slope": 35.0,
        "river_dist_m": 900.0
    }
]

RAW_CANDIDATE_SITES = [
    {
        "site_id": "SITE-001",
        "id": "SITE-001",
        "name": "Gopeshwar District Relief Campus",
        "address": "Civil Lines, Gopeshwar Town, District Chamoli, Uttarakhand 246401",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4180,
        "longitude": 79.3240,
        "site_type": "Relief Campus",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-001",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 850.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.5,
        "nearest_hospital_km": 1.5,
        "nearest_school_km": 0.8,
        "land_area_sqm": 45000.0,
        "water_lpd": 450000,
        "sanitation_cap": 4000,
        "healthcare_cap": 2500,
        "education_cap": 3500,
        "road_cap": 5000,
        "emergency_cap": 4500,
        "safety_score": 92.0,
        "suitability_score": 88.5,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-002",
        "id": "SITE-002",
        "name": "Government Polytechnic Ground, Pipalkoti",
        "address": "NH-58 Corridor, Pipalkoti, District Chamoli, Uttarakhand 246472",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4410,
        "longitude": 79.4220,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-002",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 600.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 4.2,
        "nearest_hospital_km": 4.2,
        "nearest_school_km": 0.2,
        "land_area_sqm": 22000.0,
        "water_lpd": 200000,
        "sanitation_cap": 1800,
        "healthcare_cap": 1600,
        "education_cap": 2000,
        "road_cap": 2500,
        "emergency_cap": 2000,
        "safety_score": 86.0,
        "suitability_score": 82.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-003",
        "id": "SITE-003",
        "name": "Gauchar Airstrip Relief Complex",
        "address": "Airstrip Grounds, Gauchar, District Chamoli, Uttarakhand 246429",
        "district": "Chamoli",
        "subdistrict": "Karnaprayag",
        "state": "Uttarakhand",
        "latitude": 30.2850,
        "longitude": 79.1580,
        "site_type": "Open Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-003",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 700.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.0,
        "nearest_hospital_km": 2.0,
        "nearest_school_km": 1.1,
        "land_area_sqm": 60000.0,
        "water_lpd": 500000,
        "sanitation_cap": 4800,
        "healthcare_cap": 3000,
        "education_cap": 4000,
        "road_cap": 6000,
        "emergency_cap": 6000,
        "safety_score": 95.0,
        "suitability_score": 91.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-004",
        "id": "SITE-004",
        "name": "Chamoli Sports Stadium Heights",
        "address": "Upper Heights Stadium Complex, Gopeshwar, District Chamoli, Uttarakhand 246401",
        "district": "Chamoli",
        "subdistrict": "Chamoli",
        "state": "Uttarakhand",
        "latitude": 30.4110,
        "longitude": 79.3410,
        "site_type": "Sports Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-004",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 900.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 2.8,
        "nearest_hospital_km": 2.8,
        "nearest_school_km": 0.5,
        "land_area_sqm": 18000.0,
        "water_lpd": 150000,
        "sanitation_cap": 1400,
        "healthcare_cap": 1500,
        "education_cap": 1600,
        "road_cap": 2000,
        "emergency_cap": 1800,
        "safety_score": 84.0,
        "suitability_score": 79.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-005",
        "id": "SITE-005",
        "name": "Tapovan Riverbank Lowland Park",
        "address": "Dhauliganga Riverbank Sector, Tapovan, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4910,
        "longitude": 79.6310,
        "site_type": "Open Ground",
        "source_type": "DEMONSTRATION_DATA",
        "source_url": "https://uksdma.uk.gov.in/shelters/chamoli/site-005",
        "source_reference": "UK-SDMA Hazard Audit 2026",
        "verification_status": "REJECTED_HAZARD",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": False,
        "safety_status": "REJECTED",
        "rejection_reason": "REJECTED: High Flash Flood Inundation & Landslide Runout Zone (River Distance < 100m)",
        "hazard_status": "UNSAFE_FLOOD_RUNOUT",
        "hazard_reasons": ["Inundation Zone Intersect", "Landslide Runout Area", "River Proximity Buffer < 100m"],
        "river_distance_m": 80.0,
        "road_access_status": "Poor",
        "road_accessibility": "Poor",
        "hospital_distance_km": 12.0,
        "nearest_hospital_km": 12.0,
        "nearest_school_km": 5.0,
        "land_area_sqm": 80000.0,
        "water_lpd": 800000,
        "sanitation_cap": 8000,
        "healthcare_cap": 8000,
        "education_cap": 8000,
        "road_cap": 8000,
        "emergency_cap": 8000,
        "safety_score": 12.0,
        "suitability_score": 10.0,
        "used_capacity": 0,
        "is_demonstration": True,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-006",
        "id": "SITE-006",
        "name": "Joshimath Army Staging Hub & Relief Camp",
        "address": "Upper Plateau Road, Joshimath Town, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.5590,
        "longitude": 79.5680,
        "site_type": "Emergency Staging Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/joshimath/site-006",
        "source_reference": "NDRF & SDMA Emergency Base Registry",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1200.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.2,
        "nearest_hospital_km": 1.2,
        "nearest_school_km": 0.5,
        "land_area_sqm": 35000.0,
        "water_lpd": 300000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2500,
        "road_cap": 3500,
        "emergency_cap": 3000,
        "safety_score": 89.0,
        "suitability_score": 86.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-007",
        "id": "SITE-007",
        "name": "Tapovan Upper Ridge Community Shelter",
        "address": "Safe Ridge Heights, Tapovan, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4980,
        "longitude": 79.6350,
        "site_type": "Community Centre",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/joshimath/site-007",
        "source_reference": "UK-SDMA District Shelter List 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 450.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 10.5,
        "nearest_hospital_km": 10.5,
        "nearest_school_km": 1.0,
        "land_area_sqm": 15000.0,
        "water_lpd": 150000,
        "sanitation_cap": 1200,
        "healthcare_cap": 1000,
        "education_cap": 1200,
        "road_cap": 1500,
        "emergency_cap": 1500,
        "safety_score": 88.0,
        "suitability_score": 81.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-008",
        "id": "SITE-008",
        "name": "Tharali Sub-Divisional Relief Ground",
        "address": "Main Bazar Heights, Tharali, District Chamoli, Uttarakhand 246481",
        "district": "Chamoli",
        "subdistrict": "Tharali",
        "state": "Uttarakhand",
        "latitude": 30.0680,
        "longitude": 79.5080,
        "site_type": "Government Ground",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/tharali/site-008",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 2.5,
        "nearest_hospital_km": 2.5,
        "nearest_school_km": 0.4,
        "land_area_sqm": 25000.0,
        "water_lpd": 250000,
        "sanitation_cap": 2200,
        "healthcare_cap": 1800,
        "education_cap": 2000,
        "road_cap": 2500,
        "emergency_cap": 2200,
        "safety_score": 87.0,
        "suitability_score": 83.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-009",
        "id": "SITE-009",
        "name": "Dewal Block High School Shelter",
        "address": "High School Campus, Dewal, District Chamoli, Uttarakhand 246427",
        "district": "Chamoli",
        "subdistrict": "Tharali",
        "state": "Uttarakhand",
        "latitude": 30.0250,
        "longitude": 79.6150,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/dewal/site-009",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 800.0,
        "road_access_status": "Moderate",
        "road_accessibility": "Moderate",
        "hospital_distance_km": 8.0,
        "nearest_hospital_km": 8.0,
        "nearest_school_km": 0.1,
        "land_area_sqm": 16000.0,
        "water_lpd": 160000,
        "sanitation_cap": 1400,
        "healthcare_cap": 1200,
        "education_cap": 1500,
        "road_cap": 1500,
        "emergency_cap": 1400,
        "safety_score": 85.0,
        "suitability_score": 80.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-010",
        "id": "SITE-010",
        "name": "Karnaprayag Inter College Ground",
        "address": "Alaknanda Confluence Corridor, Karnaprayag, District Chamoli, Uttarakhand 246444",
        "district": "Chamoli",
        "subdistrict": "Karnaprayag",
        "state": "Uttarakhand",
        "latitude": 30.2580,
        "longitude": 79.2150,
        "site_type": "Public School",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/karnaprayag/site-010",
        "source_reference": "UK-SDMA Master Shelter Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 550.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.8,
        "nearest_hospital_km": 1.8,
        "nearest_school_km": 0.1,
        "land_area_sqm": 28000.0,
        "water_lpd": 280000,
        "sanitation_cap": 2500,
        "healthcare_cap": 2000,
        "education_cap": 2500,
        "road_cap": 3000,
        "emergency_cap": 2500,
        "safety_score": 90.0,
        "suitability_score": 87.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-011",
        "id": "SITE-011",
        "name": "Badrinath High Altitude Transit Shelter",
        "address": "Mana Bypass Sector, Badrinath Town, District Chamoli, Uttarakhand 246422",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.7420,
        "longitude": 79.4910,
        "site_type": "Transit Shelter",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/badrinath/site-011",
        "source_reference": "UK-SDMA High Altitude Relief Register 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 400.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 3.0,
        "nearest_hospital_km": 3.0,
        "nearest_school_km": 1.5,
        "land_area_sqm": 20000.0,
        "water_lpd": 180000,
        "sanitation_cap": 1500,
        "healthcare_cap": 1200,
        "education_cap": 1500,
        "road_cap": 2000,
        "emergency_cap": 1800,
        "safety_score": 88.0,
        "suitability_score": 84.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-012",
        "id": "SITE-012",
        "name": "Raini Riverbed Flood Plain (UNSAFE TEST)",
        "address": "Rishiganga River Junction, Raini Village, District Chamoli, Uttarakhand 246443",
        "district": "Chamoli",
        "subdistrict": "Joshimath",
        "state": "Uttarakhand",
        "latitude": 30.4840,
        "longitude": 79.6920,
        "site_type": "Open Ground",
        "source_type": "DEMONSTRATION_DATA",
        "source_url": "https://uksdma.uk.gov.in/shelters/raini/site-012",
        "source_reference": "UK-SDMA Hazard Exclusion List 2026",
        "verification_status": "REJECTED_HAZARD",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": False,
        "safety_status": "REJECTED",
        "rejection_reason": "REJECTED: Severe Debris Flow & Flood Plain (River Distance 40m < 100m Buffer)",
        "hazard_status": "UNSAFE_DEBRIS_FLOW",
        "hazard_reasons": ["River Distance < 100m", "Active Debris Channel", "Flash Flood Danger Zone"],
        "river_distance_m": 40.0,
        "road_access_status": "Isolated",
        "road_accessibility": "Isolated",
        "hospital_distance_km": 15.0,
        "nearest_hospital_km": 15.0,
        "nearest_school_km": 3.0,
        "land_area_sqm": 50000.0,
        "water_lpd": 500000,
        "sanitation_cap": 5000,
        "healthcare_cap": 5000,
        "education_cap": 5000,
        "road_cap": 5000,
        "emergency_cap": 5000,
        "safety_score": 15.0,
        "suitability_score": 10.0,
        "used_capacity": 0,
        "is_demonstration": True,
        "model_version": "AASHRAY-RELOC-v2.0"
    },
    {
        "site_id": "SITE-013",
        "id": "SITE-013",
        "name": "Rishikesh IDPL Relief Complex",
        "address": "IDPL Ground Sector, Rishikesh, District Dehradun, Uttarakhand 249201",
        "district": "Dehradun",
        "subdistrict": "Rishikesh",
        "state": "Uttarakhand",
        "latitude": 30.1030,
        "longitude": 78.2930,
        "site_type": "State Relief Complex",
        "source_type": "OFFICIAL_SDMA_REGISTRY",
        "source_url": "https://uksdma.uk.gov.in/shelters/rishikesh/site-013",
        "source_reference": "Uttarakhand State Master Shelter Plan 2026",
        "verification_status": "VERIFIED_OFFICIAL",
        "last_updated": "2026-09-17T00:00:00Z",
        "data_freshness": "CURRENT",
        "is_safe": True,
        "safety_status": "SAFE_CANDIDATE",
        "hazard_status": "SAFE",
        "hazard_reasons": [],
        "river_distance_m": 1500.0,
        "road_access_status": "Good",
        "road_accessibility": "Good",
        "hospital_distance_km": 1.0,
        "nearest_hospital_km": 1.0,
        "nearest_school_km": 0.5,
        "land_area_sqm": 100000.0,
        "water_lpd": 1000000,
        "sanitation_cap": 9000,
        "healthcare_cap": 8000,
        "education_cap": 9000,
        "road_cap": 10000,
        "emergency_cap": 10000,
        "safety_score": 96.0,
        "suitability_score": 94.0,
        "used_capacity": 0,
        "rejection_reason": None,
        "is_demonstration": False,
        "model_version": "AASHRAY-RELOC-v2.0"
    }
]


DATA_SOURCES = [
    {
        "id": "DS-001",
        "source_name": "ISRO Bhuvan GIS",
        "dataset_name": "National Landslide Susceptibility Map (Himalayan Belt)",
        "purpose": "Geospatial landslide slope hazard scoring",
        "spatial_resolution": "30m DEM Grid",
        "temporal_resolution": "Seasonal / Bi-annual",
        "last_updated": "2026-05-15",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-002",
        "source_name": "ISRO MOSDAC",
        "dataset_name": "INSAT-3D Hourly Gridded Precipitation",
        "purpose": "Dynamic rainfall intensity & extreme weather simulation",
        "spatial_resolution": "0.1 deg (~10km)",
        "temporal_resolution": "Hourly",
        "last_updated": "2026-09-09 22:00 IST",
        "status": "CONNECTED"
    },
    {
        "id": "DS-003",
        "source_name": "Census India / UK-SDMA",
        "dataset_name": "District Settlement Population & Vulnerability Baseline",
        "purpose": "Population demographics, elderly/children count, households",
        "spatial_resolution": "Habitation / Village Level",
        "temporal_resolution": "Baseline",
        "last_updated": "2024-11-20",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-004",
        "source_name": "OpenStreetMap / PWD UK",
        "dataset_name": "Himalayan Mountain Road Network & Infrastructure",
        "purpose": "Accessibility routing & medical proximity",
        "spatial_resolution": "Vector Line String",
        "temporal_resolution": "Continuous",
        "last_updated": "2026-08-01",
        "status": "HISTORICAL"
    },
    {
        "id": "DS-005",
        "source_name": "AASHRAY Simulation Engine",
        "dataset_name": "Extreme Cloudburst Scenario Generator (Chamoli Pilot)",
        "purpose": "Dynamic risk recalculation & decision-support testing",
        "spatial_resolution": "100m Hydro Grid",
        "temporal_resolution": "Real-time interactive",
        "last_updated": "Active Engine",
        "status": "SIMULATED"
    }
]

INITIAL_ALERTS = [
    {
        "id": "ALT-001",
        "severity": "CRITICAL",
        "timestamp": "2026-09-11 00:15",
        "source": "IMD District Warning System",
        "location": "Chamoli & Upper Alaknanda Catchment",
        "message": "IMD Heavy to Very Heavy Rainfall Warning (Orange Alert). High Risk of Slope Instability."
    },
    {
        "id": "ALT-002",
        "severity": "WARNING",
        "timestamp": "2026-09-11 00:10",
        "source": "AASHRAY Carrying Capacity Engine",
        "location": "Gopeshwar District Relief Campus",
        "message": "Healthcare capacity bottleneck identified (Healthcare cap threshold: 2,500 persons)."
    },
    {
        "id": "ALT-003",
        "severity": "WARNING",
        "timestamp": "2026-09-10 21:15",
        "source": "Ground Field Officer Observation (NDRF-44)",
        "location": "Raini Upper Settlement Cluster",
        "message": "Active tension cracks observed 40m above residential cluster. Water seepage visible."
    }
]


RIVERS_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {"name": "Alaknanda River", "type": "Major Himalayan River"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.4960, 30.7760],
                    [79.5490, 30.6340],
                    [79.5642, 30.5564],
                    [79.4310, 30.4320],
                    [79.3360, 30.4040],
                    [79.1580, 30.2850]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Dhauliganga River", "type": "Flash Flood Drainage Channel"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.6914, 30.4852],
                    [79.6295, 30.4935],
                    [79.5642, 30.5564]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Pindar River", "type": "South Chamoli Tributary"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.6100, 30.0210],
                    [79.5020, 30.0650],
                    [79.3360, 30.4040]
                ]
            }
        }
    ]
}

ROADS_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {"name": "Badrinath Highway (NH-58)", "type": "Arterial Highway"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.1580, 30.2850],
                    [79.3360, 30.4040],
                    [79.4310, 30.4320],
                    [79.4890, 30.5180],
                    [79.5642, 30.5564],
                    [79.5490, 30.6340],
                    [79.4960, 30.7760]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {"name": "Joshimath - Malari Border Road", "type": "Strategic Mountain Corridor"},
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [79.5642, 30.5564],
                    [79.6295, 30.4935],
                    [79.6914, 30.4852]
                ]
            }
        }
    ]
}

INFRASTRUCTURE_FACILITIES = {
    "hospitals": [
        {"id": "HOSP-01", "name": "District Hospital Gopeshwar", "latitude": 30.4190, "longitude": 79.3250, "beds": 150, "icu_available": True},
        {"id": "HOSP-02", "name": "Sub-District Hospital Joshimath", "latitude": 30.5570, "longitude": 79.5650, "beds": 60, "icu_available": False},
        {"id": "HOSP-03", "name": "CHC Pipalkoti", "latitude": 30.4330, "longitude": 79.4320, "beds": 30, "icu_available": False},
        {"id": "HOSP-04", "name": "Primary Health Centre Tapovan", "latitude": 30.4940, "longitude": 79.6300, "beds": 15, "icu_available": False}
    ],
    "schools": [
        {"id": "SCH-01", "name": "Govt Inter College Joshimath", "latitude": 30.5580, "longitude": 79.5630, "capacity": 800},
        {"id": "SCH-02", "name": "Govt Polytechnic Pipalkoti", "latitude": 30.4410, "longitude": 79.4220, "capacity": 1200},
        {"id": "SCH-03", "name": "Primary School Raini", "latitude": 30.4860, "longitude": 79.6920, "capacity": 150},
        {"id": "SCH-04", "name": "GIC Gopeshwar Central", "latitude": 30.4170, "longitude": 79.3230, "capacity": 1000}
    ],
    "emergency_centres": [
        {"id": "EMERG-01", "name": "NDRF 15th Bn Base Camp, Joshimath", "latitude": 30.5550, "longitude": 79.5610, "teams_deployed": 4},
        {"id": "EMERG-02", "name": "DEOC Control Room, Gopeshwar", "latitude": 30.4185, "longitude": 79.3245, "teams_deployed": 6},
        {"id": "EMERG-03", "name": "Army Staging Hub, Gauchar Airstrip", "latitude": 30.2855, "longitude": 79.1585, "teams_deployed": 8}
    ]
}

