import React from 'react';
import { BrainCircuit, CheckCircle2, ShieldCheck } from 'lucide-react';

export const AIInsightsView: React.FC = () => {
  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-extrabold text-slate-100">AI Explainability & Model Transparency</h1>
        <p className="text-xs text-slate-400 mt-1">
          Auditable decision logs explaining recommendation rationales and data evidence confidence ratings.
        </p>
      </div>

      <div className="bg-command-card border border-command-border p-6 rounded-xl space-y-4">
        <h3 className="text-sm font-bold text-slate-200 border-b border-command-border pb-2 flex items-center space-x-2">
          <BrainCircuit className="w-4 h-4 text-blue-400" />
          <span>Scientific Honesty & Decision Support Policy</span>
        </h3>

        <div className="space-y-3 text-xs text-slate-300 leading-relaxed">
          <p>
            AASHRAY operates as an <b>explainable decision-support platform</b> rather than an autonomous evacuation authority. Every recommendation generated by the platform remains fully auditable down to individual component inputs.
          </p>
          <div className="p-3 bg-slate-900 rounded border border-slate-800 space-y-1">
            <div className="font-bold text-amber-400">Model Version & Calibration:</div>
            <div className="text-slate-400">
              Prototype Multi-Hazard Risk & Optimization Engine v1.0.4. Requires calibration with authority-validated historical disaster logs prior to operational deployment.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
